hacienda_url: "https://apitest.dtes.mh.gob.sv/fesv/recepciondte"
port: "4000"
database_url: "postgres://your_username:your_password@localhost:5432/cuentas?sslmode=disable"
firmador_url: "http://167.172.230.154:8113"
firmador_timeout: 30s
firmador_retry_max: 3
firmador_retry_wait_min: 1s
firmador_retry_wait_max: 5s
