ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS cod_actividad VARCHAR(6),
ADD COLUMN IF NOT EXISTS desc_actividad VARCHAR(150),
ADD COLUMN IF NOT EXISTS nombre_comercial VARCHAR(150),
ADD COLUMN IF NOT EXISTS telefono VARCHAR(30),
ADD COLUMN IF NOT EXISTS correo VARCHAR(100);
