package codigos

type ActivityCategory struct {
	Code       string   `json:"code"`
	Name       string   `json:"name"`
	ParentCode string   `json:"parent_code,omitempty"`
	Level      int      `json:"level"` // 1=sector, 2=subsector, 3=group
	Keywords   []string `json:"keywords,omitempty"`
}

// Categories defines the hierarchical structure of economic activities
var ActividadEconomicaCategories = map[string]ActivityCategory{
	// Level 1: Major Sectors
	"01": {
		Code:     "01",
		Name:     "AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA",
		Level:    1,
		Keywords: []string{"agricultura", "ganadería", "silvicultura", "pesca", "cultivo", "cosecha", "granja", "finca", "campo", "animales", "ganado", "bosque", "madera", "pescado", "acuicultura"},
	},
	"02": {
		Code:     "02",
		Name:     "SILVICULTURA Y EXTRACCIÓN DE MADERA",
		Level:    1,
		Keywords: []string{"silvicultura", "madera", "bosque", "tala", "aserradero", "forestal", "árboles", "leña"},
	},
	"03": {
		Code:     "03",
		Name:     "PESCA Y ACUICULTURA",
		Level:    1,
		Keywords: []string{"pesca", "acuicultura", "pescado", "camarón", "mariscos", "embarcación", "lancha", "mar", "río", "lago"},
	},
	"05": {
		Code:     "05",
		Name:     "EXPLOTACIÓN DE MINAS Y CANTERAS",
		Level:    1,
		Keywords: []string{"minería", "minas", "canteras", "extracción", "minerales", "piedra", "arena", "grava", "oro", "plata"},
	},
	"10": {
		Code:     "10",
		Name:     "ELABORACIÓN DE PRODUCTOS ALIMENTICIOS",
		Level:    1,
		Keywords: []string{"alimentos", "comida", "procesamiento", "empaque", "envasado", "producción", "fábrica", "planta", "elaboración", "alimenticio"},
	},
	"11": {
		Code:     "11",
		Name:     "ELABORACIÓN DE BEBIDAS",
		Level:    1,
		Keywords: []string{"bebidas", "refrescos", "jugos", "agua", "gaseosas", "cerveza", "licores", "vinos", "embotelladora"},
	},
	"12": {
		Code:     "12",
		Name:     "ELABORACIÓN DE PRODUCTOS DE TABACO",
		Level:    1,
		Keywords: []string{"tabaco", "cigarros", "cigarrillos", "puros"},
	},
	"13": {
		Code:     "13",
		Name:     "FABRICACIÓN DE PRODUCTOS TEXTILES",
		Level:    1,
		Keywords: []string{"textiles", "telas", "hilados", "tejidos", "fibras", "algodón", "confección"},
	},
	"14": {
		Code:     "14",
		Name:     "FABRICACIÓN DE PRENDAS DE VESTIR",
		Level:    1,
		Keywords: []string{"ropa", "prendas", "vestir", "confección", "maquila", "camisas", "pantalones", "vestidos", "uniformes", "costura"},
	},
	"15": {
		Code:     "15",
		Name:     "FABRICACIÓN DE CUEROS Y PRODUCTOS CONEXOS",
		Level:    1,
		Keywords: []string{"cuero", "piel", "calzado", "zapatos", "marroquinería", "carteras", "bolsos", "curtiembre", "talabartería"},
	},
	"16": {
		Code:     "16",
		Name:     "PRODUCCIÓN DE MADERA Y FABRICACIÓN DE PRODUCTOS DE MADERA",
		Level:    1,
		Keywords: []string{"madera", "carpintería", "muebles", "aserradero", "tablones", "tablas", "puertas", "ventanas"},
	},
	"17": {
		Code:     "17",
		Name:     "FABRICACIÓN DE PAPEL Y DE PRODUCTOS DE PAPEL",
		Level:    1,
		Keywords: []string{"papel", "cartón", "cajas", "envases", "empaque", "servilletas", "papel higiénico"},
	},
	"18": {
		Code:     "18",
		Name:     "IMPRESIÓN Y REPRODUCCIÓN DE GRABACIONES",
		Level:    1,
		Keywords: []string{"impresión", "imprenta", "impresora", "grabación", "reproducción", "copias"},
	},
	"19": {
		Code:     "19",
		Name:     "FABRICACIÓN DE COQUE Y DE PRODUCTOS DE LA REFINACIÓN DE PETRÓLEO",
		Level:    1,
		Keywords: []string{"petróleo", "refinación", "combustibles", "gasolina", "diesel", "aceites"},
	},
	"20": {
		Code:     "20",
		Name:     "FABRICACIÓN DE SUSTANCIAS Y PRODUCTOS QUÍMICOS",
		Level:    1,
		Keywords: []string{"químicos", "productos químicos", "sustancias", "pinturas", "barnices", "plaguicidas", "fertilizantes", "plásticos"},
	},
	"21": {
		Code:     "21",
		Name:     "FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS",
		Level:    1,
		Keywords: []string{"farmacéuticos", "medicamentos", "medicina", "drogas", "laboratorio", "farmacia"},
	},
	"22": {
		Code:     "22",
		Name:     "FABRICACIÓN DE PRODUCTOS DE CAUCHO Y PLÁSTICO",
		Level:    1,
		Keywords: []string{"caucho", "plástico", "hule", "llantas", "neumáticos", "envases plásticos", "bolsas"},
	},
	"23": {
		Code:     "23",
		Name:     "FABRICACIÓN DE PRODUCTOS MINERALES NO METÁLICOS",
		Level:    1,
		Keywords: []string{"minerales", "cemento", "concreto", "vidrio", "cerámica", "ladrillos", "bloques", "azulejos", "porcelana"},
	},
	"24": {
		Code:     "24",
		Name:     "FABRICACIÓN DE METALES COMUNES",
		Level:    1,
		Keywords: []string{"metales", "hierro", "acero", "fundición", "metalurgia", "siderúrgica"},
	},
	"25": {
		Code:     "25",
		Name:     "FABRICACIÓN DE PRODUCTOS DERIVADOS DE METAL",
		Level:    1,
		Keywords: []string{"metal", "metálicos", "estructura metálica", "herramientas", "utensilios", "cerrajería", "soldadura"},
	},
	"26": {
		Code:     "26",
		Name:     "FABRICACIÓN DE PRODUCTOS DE INFORMÁTICA, ELECTRÓNICA Y ÓPTICA",
		Level:    1,
		Keywords: []string{"electrónica", "informática", "computadoras", "componentes electrónicos", "equipos electrónicos", "óptica"},
	},
	"27": {
		Code:     "27",
		Name:     "FABRICACIÓN DE EQUIPO ELÉCTRICO",
		Level:    1,
		Keywords: []string{"eléctrico", "equipos eléctricos", "cables", "alambres", "instalaciones eléctricas", "electricidad"},
	},
	"28": {
		Code:     "28",
		Name:     "FABRICACIÓN DE MAQUINARIA Y EQUIPO",
		Level:    1,
		Keywords: []string{"maquinaria", "equipo", "máquinas", "bombas", "motores", "herramientas"},
	},
	"29": {
		Code:     "29",
		Name:     "FABRICACIÓN DE VEHÍCULOS AUTOMOTORES, REMOLQUES Y SEMIRREMOLQUES",
		Level:    1,
		Keywords: []string{"vehículos", "automotores", "autos", "carros", "camiones", "remolques", "ensamblaje", "carrocerías"},
	},
	"30": {
		Code:     "30",
		Name:     "FABRICACIÓN DE OTROS TIPOS DE EQUIPO DE TRANSPORTE",
		Level:    1,
		Keywords: []string{"transporte", "barcos", "embarcaciones", "bicicletas", "aeronaves"},
	},
	"31": {
		Code:     "31",
		Name:     "FABRICACIÓN DE MUEBLES",
		Level:    1,
		Keywords: []string{"muebles", "mueblería", "carpintería", "sillas", "mesas", "camas", "sofás", "colchones"},
	},
	"32": {
		Code:     "32",
		Name:     "OTRAS INDUSTRIAS MANUFACTURERAS",
		Level:    1,
		Keywords: []string{"manufactura", "fabricación", "joyería", "joyas", "bisutería", "instrumentos musicales", "artesanías", "juguetes"},
	},
	"33": {
		Code:     "33",
		Name:     "REPARACIÓN E INSTALACIÓN DE MAQUINARIA Y EQUIPO",
		Level:    1,
		Keywords: []string{"reparación", "instalación", "mantenimiento", "taller", "servicio técnico"},
	},
	"35": {
		Code:     "35",
		Name:     "SUMINISTROS DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",
		Level:    1,
		Keywords: []string{"electricidad", "energía eléctrica", "gas", "suministro", "distribución", "generación"},
	},
	"36": {
		Code:     "36",
		Name:     "CAPTACIÓN, TRATAMIENTO Y SUMINISTRO DE AGUA",
		Level:    1,
		Keywords: []string{"agua", "agua potable", "suministro de agua", "distribución", "tratamiento"},
	},
	"37": {
		Code:     "37",
		Name:     "EVACUACIÓN DE AGUAS RESIDUALES",
		Level:    1,
		Keywords: []string{"aguas residuales", "alcantarillado", "drenaje", "evacuación"},
	},
	"38": {
		Code:     "38",
		Name:     "RECOLECCIÓN, TRATAMIENTO Y ELIMINACIÓN DE DESECHOS; RECICLAJE",
		Level:    1,
		Keywords: []string{"desechos", "basura", "residuos", "reciclaje", "recolección", "tratamiento", "eliminación"},
	},
	"39": {
		Code:     "39",
		Name:     "ACTIVIDADES DE SANEAMIENTO Y OTROS SERVICIOS DE GESTIÓN DE DESECHOS",
		Level:    1,
		Keywords: []string{"saneamiento", "limpieza", "desinfección", "fumigación", "gestión de desechos"},
	},
	"41": {
		Code:     "41",
		Name:     "CONSTRUCCIÓN DE EDIFICIOS",
		Level:    1,
		Keywords: []string{"construcción", "edificios", "casas", "viviendas", "apartamentos", "constructora", "albañilería", "obra"},
	},
	"42": {
		Code:     "42",
		Name:     "OBRAS DE INGENIERÍA CIVIL",
		Level:    1,
		Keywords: []string{"ingeniería civil", "obras", "carreteras", "puentes", "infraestructura", "construcción"},
	},
	"43": {
		Code:     "43",
		Name:     "ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCIÓN",
		Level:    1,
		Keywords: []string{"construcción", "especializada", "electricidad", "fontanería", "plomería", "pintura", "acabados", "instalaciones"},
	},
	"45": {
		Code:     "45",
		Name:     "COMERCIO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS",
		Level:    1,
		Keywords: []string{"vehículos", "autos", "carros", "motos", "motocicletas", "venta de autos", "taller mecánico", "reparación", "repuestos"},
	},
	"46": {
		Code:     "46",
		Name:     "COMERCIO AL POR MAYOR",
		Level:    1,
		Keywords: []string{"mayorista", "por mayor", "distribución", "distribuidor", "almacén", "bodega"},
	},
	"47": {
		Code:     "47",
		Name:     "COMERCIO AL POR MENOR",
		Level:    1,
		Keywords: []string{"minorista", "por menor", "tienda", "negocio", "comercio", "venta", "retail", "supermercado"},
	},
	"49": {
		Code:     "49",
		Name:     "TRANSPORTE POR VÍA TERRESTRE Y TRANSPORTE POR TUBERÍAS",
		Level:    1,
		Keywords: []string{"transporte", "terrestre", "buses", "microbuses", "camiones", "carga", "pasajeros", "taxis"},
	},
	"50": {
		Code:     "50",
		Name:     "TRANSPORTE POR VÍA ACUÁTICA",
		Level:    1,
		Keywords: []string{"transporte", "acuático", "marítimo", "barcos", "lanchas", "embarcaciones", "fluvial"},
	},
	"51": {
		Code:     "51",
		Name:     "TRANSPORTE POR VÍA AÉREA",
		Level:    1,
		Keywords: []string{"transporte", "aéreo", "aviones", "aviación", "vuelos", "aerolínea"},
	},
	"52": {
		Code:     "52",
		Name:     "ALMACENAMIENTO Y ACTIVIDADES DE APOYO AL TRANSPORTE",
		Level:    1,
		Keywords: []string{"almacenamiento", "bodega", "depósito", "logística", "apoyo al transporte", "estacionamiento", "garaje"},
	},
	"53": {
		Code:     "53",
		Name:     "ACTIVIDADES POSTALES Y DE MENSAJERÍA",
		Level:    1,
		Keywords: []string{"postal", "correo", "mensajería", "paquetería", "encomiendas", "courier"},
	},
	"55": {
		Code:     "55",
		Name:     "ACTIVIDADES DE ALOJAMIENTO",
		Level:    1,
		Keywords: []string{"alojamiento", "hoteles", "hotel", "hospedaje", "posada", "motel", "pensión"},
	},
	"56": {
		Code:     "56",
		Name:     "ACTIVIDADES DE SERVICIO DE COMIDAS Y BEBIDAS",
		Level:    1,
		Keywords: []string{"restaurantes", "restaurante", "comida", "bebidas", "pupusería", "comedores", "cafetería", "bar", "food service"},
	},
	"58": {
		Code:     "58",
		Name:     "ACTIVIDADES DE EDICIÓN",
		Level:    1,
		Keywords: []string{"edición", "editorial", "publicación", "libros", "revistas", "periódicos"},
	},
	"59": {
		Code:     "59",
		Name:     "PRODUCCIÓN DE PELÍCULAS Y PROGRAMAS DE TELEVISIÓN",
		Level:    1,
		Keywords: []string{"películas", "cine", "televisión", "video", "producción audiovisual", "grabación"},
	},
	"60": {
		Code:     "60",
		Name:     "ACTIVIDADES DE PROGRAMACIÓN Y TRANSMISIÓN",
		Level:    1,
		Keywords: []string{"programación", "transmisión", "radio", "televisión", "difusión"},
	},
	"61": {
		Code:     "61",
		Name:     "TELECOMUNICACIONES",
		Level:    1,
		Keywords: []string{"telecomunicaciones", "telefonía", "internet", "celular", "móvil", "comunicaciones"},
	},
	"62": {
		Code:     "62",
		Name:     "PROGRAMACIÓN INFORMÁTICA Y CONSULTORÍA",
		Level:    1,
		Keywords: []string{"informática", "programación", "software", "desarrollo", "sistemas", "IT", "tecnología", "consultoría informática"},
	},
	"63": {
		Code:     "63",
		Name:     "ACTIVIDADES DE SERVICIOS DE INFORMACIÓN",
		Level:    1,
		Keywords: []string{"información", "servicios de información", "datos", "procesamiento de datos", "portales web"},
	},
	"64": {
		Code:     "64",
		Name:     "ACTIVIDADES DE SERVICIOS FINANCIEROS",
		Level:    1,
		Keywords: []string{"financieros", "bancos", "banco", "crédito", "préstamos", "finanzas", "inversiones", "remesas"},
	},
	"65": {
		Code:     "65",
		Name:     "SEGUROS Y FONDOS DE PENSIONES",
		Level:    1,
		Keywords: []string{"seguros", "aseguradora", "pólizas", "pensiones", "AFP", "jubilación"},
	},
	"66": {
		Code:     "66",
		Name:     "ACTIVIDADES AUXILIARES DE SERVICIOS FINANCIEROS",
		Level:    1,
		Keywords: []string{"financieros", "auxiliares", "bolsa de valores", "corredores", "cambio de moneda", "casa de cambio"},
	},
	"68": {
		Code:     "68",
		Name:     "ACTIVIDADES INMOBILIARIAS",
		Level:    1,
		Keywords: []string{"inmobiliaria", "bienes raíces", "propiedades", "alquiler", "arrendamiento", "venta de propiedades"},
	},
	"69": {
		Code:     "69",
		Name:     "ACTIVIDADES JURÍDICAS Y CONTABLES",
		Level:    1,
		Keywords: []string{"jurídicas", "abogados", "legal", "contables", "contador", "contabilidad", "auditoría"},
	},
	"70": {
		Code:     "70",
		Name:     "ACTIVIDADES DE OFICINAS CENTRALES Y CONSULTORÍA DE GESTIÓN",
		Level:    1,
		Keywords: []string{"consultoría", "gestión", "administración", "asesoría empresarial", "oficinas centrales"},
	},
	"71": {
		Code:     "71",
		Name:     "ACTIVIDADES DE ARQUITECTURA E INGENIERÍA",
		Level:    1,
		Keywords: []string{"arquitectura", "arquitecto", "ingeniería", "ingeniero", "diseño", "planos", "proyectos"},
	},
	"72": {
		Code:     "72",
		Name:     "INVESTIGACIÓN CIENTÍFICA Y DESARROLLO",
		Level:    1,
		Keywords: []string{"investigación", "científica", "desarrollo", "laboratorio", "I+D"},
	},
	"73": {
		Code:     "73",
		Name:     "PUBLICIDAD Y ESTUDIOS DE MERCADO",
		Level:    1,
		Keywords: []string{"publicidad", "marketing", "mercadeo", "estudios de mercado", "encuestas", "agencia publicitaria"},
	},
	"74": {
		Code:     "74",
		Name:     "OTRAS ACTIVIDADES PROFESIONALES Y TÉCNICAS",
		Level:    1,
		Keywords: []string{"profesionales", "técnicas", "diseño", "fotografía", "traducción", "servicios profesionales"},
	},
	"75": {
		Code:     "75",
		Name:     "ACTIVIDADES VETERINARIAS",
		Level:    1,
		Keywords: []string{"veterinaria", "veterinario", "animales", "mascotas", "clínica veterinaria"},
	},
	"77": {
		Code:     "77",
		Name:     "ACTIVIDADES DE ALQUILER Y ARRENDAMIENTO",
		Level:    1,
		Keywords: []string{"alquiler", "arrendamiento", "renta", "rental", "equipos", "vehículos"},
	},
	"78": {
		Code:     "78",
		Name:     "ACTIVIDADES DE EMPLEO",
		Level:    1,
		Keywords: []string{"empleo", "recursos humanos", "reclutamiento", "contratación", "agencia de empleo"},
	},
	"79": {
		Code:     "79",
		Name:     "ACTIVIDADES DE AGENCIAS DE VIAJES Y OPERADORES TURÍSTICOS",
		Level:    1,
		Keywords: []string{"viajes", "agencia de viajes", "turismo", "tours", "operador turístico"},
	},
	"80": {
		Code:     "80",
		Name:     "ACTIVIDADES DE INVESTIGACIÓN Y SEGURIDAD",
		Level:    1,
		Keywords: []string{"seguridad", "vigilancia", "investigación", "guardias", "seguridad privada"},
	},
	"81": {
		Code:     "81",
		Name:     "ACTIVIDADES DE SERVICIOS A EDIFICIOS Y PAISAJISMO",
		Level:    1,
		Keywords: []string{"edificios", "limpieza", "mantenimiento", "paisajismo", "jardinería", "fumigación"},
	},
	"82": {
		Code:     "82",
		Name:     "ACTIVIDADES ADMINISTRATIVAS Y DE APOYO DE OFICINAS",
		Level:    1,
		Keywords: []string{"administrativas", "oficinas", "apoyo", "call center", "secretaría", "fotocopiado"},
	},
	"84": {
		Code:     "84",
		Name:     "ADMINISTRACIÓN PÚBLICA Y DEFENSA",
		Level:    1,
		Keywords: []string{"pública", "gobierno", "administración pública", "alcaldía", "municipal", "defensa", "ministerio"},
	},
	"85": {
		Code:     "85",
		Name:     "ENSEÑANZA",
		Level:    1,
		Keywords: []string{"educación", "enseñanza", "escuela", "colegio", "universidad", "instituto", "academia", "clases", "maestro", "profesor"},
	},
	"86": {
		Code:     "86",
		Name:     "ACTIVIDADES DE ATENCIÓN A LA SALUD HUMANA",
		Level:    1,
		Keywords: []string{"salud", "médicos", "clínica", "hospital", "consultorio", "doctor", "odontología", "dentista"},
	},
	"87": {
		Code:     "87",
		Name:     "ACTIVIDADES DE ATENCIÓN DE ENFERMERÍA EN INSTITUCIONES",
		Level:    1,
		Keywords: []string{"enfermería", "asilos", "residencias", "atención", "cuidado", "ancianos"},
	},
	"88": {
		Code:     "88",
		Name:     "ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO",
		Level:    1,
		Keywords: []string{"asistencia social", "servicios sociales", "ayuda social", "ONG"},
	},
	"90": {
		Code:     "90",
		Name:     "ACTIVIDADES CREATIVAS, ARTÍSTICAS Y DE ENTRETENIMIENTO",
		Level:    1,
		Keywords: []string{"artísticas", "arte", "entretenimiento", "espectáculos", "teatro", "música", "cultural"},
	},
	"91": {
		Code:     "91",
		Name:     "ACTIVIDADES DE BIBLIOTECAS, ARCHIVOS Y MUSEOS",
		Level:    1,
		Keywords: []string{"bibliotecas", "museos", "archivos", "cultura", "patrimonio"},
	},
	"92": {
		Code:     "92",
		Name:     "ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS",
		Level:    1,
		Keywords: []string{"juegos", "apuestas", "casino", "lotería", "azar"},
	},
	"93": {
		Code:     "93",
		Name:     "ACTIVIDADES DEPORTIVAS Y DE ESPARCIMIENTO",
		Level:    1,
		Keywords: []string{"deportes", "deportivas", "gimnasio", "esparcimiento", "recreación", "parques", "entretenimiento"},
	},
	"94": {
		Code:     "94",
		Name:     "ACTIVIDADES DE ASOCIACIONES",
		Level:    1,
		Keywords: []string{"asociaciones", "organizaciones", "sindicatos", "cámaras", "gremios", "federaciones"},
	},
	"95": {
		Code:     "95",
		Name:     "REPARACIÓN DE COMPUTADORAS Y ENSERES PERSONALES",
		Level:    1,
		Keywords: []string{"reparación", "computadoras", "celulares", "teléfonos", "electrónicos", "servicio técnico", "arreglo"},
	},
	"96": {
		Code:     "96",
		Name:     "OTRAS ACTIVIDADES DE SERVICIOS PERSONALES",
		Level:    1,
		Keywords: []string{"servicios personales", "peluquería", "salón de belleza", "lavandería", "sauna", "spa", "funeraria"},
	},
	"97": {
		Code:     "97",
		Name:     "ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES",
		Level:    1,
		Keywords: []string{"hogares", "empleadores", "doméstico", "empleada doméstica", "servicio doméstico"},
	},
	"98": {
		Code:     "98",
		Name:     "ACTIVIDADES INDIFERENCIADAS DE PRODUCCIÓN DE BIENES Y SERVICIOS",
		Level:    1,
		Keywords: []string{"hogares", "producción doméstica", "autoconsumo"},
	},
	"99": {
		Code:     "99",
		Name:     "ACTIVIDADES DE ORGANIZACIONES EXTRATERRITORIALES",
		Level:    1,
		Keywords: []string{"extraterritoriales", "organizaciones internacionales", "embajadas", "consulados"},
	},
	"100": {
		Code:     "100",
		Name:     "EMPLEADOS Y OTRAS PERSONAS NATURALES",
		Level:    1,
		Keywords: []string{"empleados", "personas naturales", "individuos", "trabajadores", "asalariados"},
	},
}
